<template>
    <div>
        <defer-render :width="'300px'" :height="'300px'">
            <div>xxxxx</div>
            <div>xxxxx</div>
            <div>xxxxx</div>
            <div>xxxxx</div>
            <div>xxxxx</div>
            <div>xxxxx</div>
            <div>xxxxx</div>
            <div>xxxxx</div>
            <div>xxxxx</div>
            <div>xxxxx</div>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <child></child>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
        <defer-render>
            <div>xxxxx</div>
        </defer-render>
    </div>
</template>

<script>
    import deferRender from '../src/defer-render.vue'
    import child from './child.vue'

    export default {
        components: {
            'defer-render': deferRender,
            'child': child
        }
    }
</script>
